const TYPES = {
  String: '',
  Number: 0,
  BigInt: 1n,
  Boolean: false,
  Null: null,
  Undefined: undefined,
  Symbol: Symbol(),
  Array: [],
  Object: {},
  RegExp: new RegExp(),
  Date: new Date(),
  Set: new Set(),
  WeakSet: new WeakSet(),
  Map: new Map(),
  WeakMap: new WeakMap(),
  Error: new Error(),
  ArrayBuffer: new ArrayBuffer(32),
  DataView: new DataView(new ArrayBuffer(32)),
  Int8Array: new Int8Array(new ArrayBuffer(32)),
  Uint8Array: new Uint8Array(new ArrayBuffer(32)),
  Int16Array: new Int16Array(new ArrayBuffer(32)),
  Uint16Array: new Uint16Array(new ArrayBuffer(32)),
  Int32Array: new Int32Array(new ArrayBuffer(32)),
  Uint32Array: new Uint32Array(new ArrayBuffer(32)),
  Float32Array: new Float32Array(new ArrayBuffer(32)),
  Float64Array: new Float64Array(new ArrayBuffer(32)),
  Function: () => {},
  NaN: NaN,
}

exports.TYPES = TYPES
